/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.9
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.com.namsor.sdk2.model
{
    /// <summary>
    /// APIPeriodUsageOut
    /// </summary>
    [DataContract]
    public partial class APIPeriodUsageOut :  IEquatable<APIPeriodUsageOut>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APIPeriodUsageOut" /> class.
        /// </summary>
        /// <param name="subscription">subscription.</param>
        /// <param name="billingPeriod">billingPeriod.</param>
        /// <param name="overageExclTax">overageExclTax.</param>
        /// <param name="overageInclTax">overageInclTax.</param>
        /// <param name="overageCurrency">overageCurrency.</param>
        /// <param name="overageQuantity">overageQuantity.</param>
        public APIPeriodUsageOut(APIPlanSubscriptionOut subscription = default(APIPlanSubscriptionOut), APIBillingPeriodUsageOut billingPeriod = default(APIBillingPeriodUsageOut), double? overageExclTax = default(double?), double? overageInclTax = default(double?), string overageCurrency = default(string), long? overageQuantity = default(long?))
        {
            this.Subscription = subscription;
            this.BillingPeriod = billingPeriod;
            this.OverageExclTax = overageExclTax;
            this.OverageInclTax = overageInclTax;
            this.OverageCurrency = overageCurrency;
            this.OverageQuantity = overageQuantity;
        }
        
        /// <summary>
        /// Gets or Sets Subscription
        /// </summary>
        [DataMember(Name="subscription", EmitDefaultValue=false)]
        public APIPlanSubscriptionOut Subscription { get; set; }

        /// <summary>
        /// Gets or Sets BillingPeriod
        /// </summary>
        [DataMember(Name="billingPeriod", EmitDefaultValue=false)]
        public APIBillingPeriodUsageOut BillingPeriod { get; set; }

        /// <summary>
        /// Gets or Sets OverageExclTax
        /// </summary>
        [DataMember(Name="overageExclTax", EmitDefaultValue=false)]
        public double? OverageExclTax { get; set; }

        /// <summary>
        /// Gets or Sets OverageInclTax
        /// </summary>
        [DataMember(Name="overageInclTax", EmitDefaultValue=false)]
        public double? OverageInclTax { get; set; }

        /// <summary>
        /// Gets or Sets OverageCurrency
        /// </summary>
        [DataMember(Name="overageCurrency", EmitDefaultValue=false)]
        public string OverageCurrency { get; set; }

        /// <summary>
        /// Gets or Sets OverageQuantity
        /// </summary>
        [DataMember(Name="overageQuantity", EmitDefaultValue=false)]
        public long? OverageQuantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class APIPeriodUsageOut {\n");
            sb.Append("  Subscription: ").Append(Subscription).Append("\n");
            sb.Append("  BillingPeriod: ").Append(BillingPeriod).Append("\n");
            sb.Append("  OverageExclTax: ").Append(OverageExclTax).Append("\n");
            sb.Append("  OverageInclTax: ").Append(OverageInclTax).Append("\n");
            sb.Append("  OverageCurrency: ").Append(OverageCurrency).Append("\n");
            sb.Append("  OverageQuantity: ").Append(OverageQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as APIPeriodUsageOut);
        }

        /// <summary>
        /// Returns true if APIPeriodUsageOut instances are equal
        /// </summary>
        /// <param name="input">Instance of APIPeriodUsageOut to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(APIPeriodUsageOut input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Subscription == input.Subscription ||
                    (this.Subscription != null &&
                    this.Subscription.Equals(input.Subscription))
                ) && 
                (
                    this.BillingPeriod == input.BillingPeriod ||
                    (this.BillingPeriod != null &&
                    this.BillingPeriod.Equals(input.BillingPeriod))
                ) && 
                (
                    this.OverageExclTax == input.OverageExclTax ||
                    (this.OverageExclTax != null &&
                    this.OverageExclTax.Equals(input.OverageExclTax))
                ) && 
                (
                    this.OverageInclTax == input.OverageInclTax ||
                    (this.OverageInclTax != null &&
                    this.OverageInclTax.Equals(input.OverageInclTax))
                ) && 
                (
                    this.OverageCurrency == input.OverageCurrency ||
                    (this.OverageCurrency != null &&
                    this.OverageCurrency.Equals(input.OverageCurrency))
                ) && 
                (
                    this.OverageQuantity == input.OverageQuantity ||
                    (this.OverageQuantity != null &&
                    this.OverageQuantity.Equals(input.OverageQuantity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Subscription != null)
                    hashCode = hashCode * 59 + this.Subscription.GetHashCode();
                if (this.BillingPeriod != null)
                    hashCode = hashCode * 59 + this.BillingPeriod.GetHashCode();
                if (this.OverageExclTax != null)
                    hashCode = hashCode * 59 + this.OverageExclTax.GetHashCode();
                if (this.OverageInclTax != null)
                    hashCode = hashCode * 59 + this.OverageInclTax.GetHashCode();
                if (this.OverageCurrency != null)
                    hashCode = hashCode * 59 + this.OverageCurrency.GetHashCode();
                if (this.OverageQuantity != null)
                    hashCode = hashCode * 59 + this.OverageQuantity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
