/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.8
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.com.namsor.sdk2.model
{
    /// <summary>
    /// BillingHistoryOut
    /// </summary>
    [DataContract]
    public partial class BillingHistoryOut :  IEquatable<BillingHistoryOut>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingHistoryOut" /> class.
        /// </summary>
        /// <param name="stripeInvoices">stripeInvoices.</param>
        /// <param name="corporateInvoices">corporateInvoices.</param>
        public BillingHistoryOut(List<InvoiceOut> stripeInvoices = default(List<InvoiceOut>), List<InvoiceOut> corporateInvoices = default(List<InvoiceOut>))
        {
            this.StripeInvoices = stripeInvoices;
            this.CorporateInvoices = corporateInvoices;
        }
        
        /// <summary>
        /// Gets or Sets StripeInvoices
        /// </summary>
        [DataMember(Name="stripeInvoices", EmitDefaultValue=false)]
        public List<InvoiceOut> StripeInvoices { get; set; }

        /// <summary>
        /// Gets or Sets CorporateInvoices
        /// </summary>
        [DataMember(Name="corporateInvoices", EmitDefaultValue=false)]
        public List<InvoiceOut> CorporateInvoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BillingHistoryOut {\n");
            sb.Append("  StripeInvoices: ").Append(StripeInvoices).Append("\n");
            sb.Append("  CorporateInvoices: ").Append(CorporateInvoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BillingHistoryOut);
        }

        /// <summary>
        /// Returns true if BillingHistoryOut instances are equal
        /// </summary>
        /// <param name="input">Instance of BillingHistoryOut to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BillingHistoryOut input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StripeInvoices == input.StripeInvoices ||
                    this.StripeInvoices != null &&
                    this.StripeInvoices.SequenceEqual(input.StripeInvoices)
                ) && 
                (
                    this.CorporateInvoices == input.CorporateInvoices ||
                    this.CorporateInvoices != null &&
                    this.CorporateInvoices.SequenceEqual(input.CorporateInvoices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StripeInvoices != null)
                    hashCode = hashCode * 59 + this.StripeInvoices.GetHashCode();
                if (this.CorporateInvoices != null)
                    hashCode = hashCode * 59 + this.CorporateInvoices.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
