/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.com.namsor.sdk2.model
{
    /// <summary>
    /// ProperNounCategorizedOut
    /// </summary>
    [DataContract]
    public partial class ProperNounCategorizedOut :  IEquatable<ProperNounCategorizedOut>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProperNounCategorizedOut" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="commonType">commonType.</param>
        /// <param name="commonTypeAlt">commonTypeAlt.</param>
        /// <param name="score">score.</param>
        public ProperNounCategorizedOut(string id = default(string), string name = default(string), string commonType = default(string), string commonTypeAlt = default(string), double? score = default(double?))
        {
            this.Id = id;
            this.Name = name;
            this.CommonType = commonType;
            this.CommonTypeAlt = commonTypeAlt;
            this.Score = score;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CommonType
        /// </summary>
        [DataMember(Name="commonType", EmitDefaultValue=false)]
        public string CommonType { get; set; }

        /// <summary>
        /// Gets or Sets CommonTypeAlt
        /// </summary>
        [DataMember(Name="commonTypeAlt", EmitDefaultValue=false)]
        public string CommonTypeAlt { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [DataMember(Name="score", EmitDefaultValue=false)]
        public double? Score { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProperNounCategorizedOut {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CommonType: ").Append(CommonType).Append("\n");
            sb.Append("  CommonTypeAlt: ").Append(CommonTypeAlt).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProperNounCategorizedOut);
        }

        /// <summary>
        /// Returns true if ProperNounCategorizedOut instances are equal
        /// </summary>
        /// <param name="input">Instance of ProperNounCategorizedOut to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProperNounCategorizedOut input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CommonType == input.CommonType ||
                    (this.CommonType != null &&
                    this.CommonType.Equals(input.CommonType))
                ) && 
                (
                    this.CommonTypeAlt == input.CommonTypeAlt ||
                    (this.CommonTypeAlt != null &&
                    this.CommonTypeAlt.Equals(input.CommonTypeAlt))
                ) && 
                (
                    this.Score == input.Score ||
                    (this.Score != null &&
                    this.Score.Equals(input.Score))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.CommonType != null)
                    hashCode = hashCode * 59 + this.CommonType.GetHashCode();
                if (this.CommonTypeAlt != null)
                    hashCode = hashCode * 59 + this.CommonTypeAlt.GetHashCode();
                if (this.Score != null)
                    hashCode = hashCode * 59 + this.Score.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
