/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.9
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.namsor.sdk2.api;
using Org.OpenAPITools.com.namsor.sdk2.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing FirstLastNameOriginedOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FirstLastNameOriginedOutTests
    {
        // TODO uncomment below to declare an instance variable for FirstLastNameOriginedOut
        //private FirstLastNameOriginedOut instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FirstLastNameOriginedOut
            //instance = new FirstLastNameOriginedOut();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FirstLastNameOriginedOut
        /// </summary>
        [Test]
        public void FirstLastNameOriginedOutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FirstLastNameOriginedOut
            //Assert.IsInstanceOfType<FirstLastNameOriginedOut> (instance, "variable 'instance' is a FirstLastNameOriginedOut");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'CountryOrigin'
        /// </summary>
        [Test]
        public void CountryOriginTest()
        {
            // TODO unit test for the property 'CountryOrigin'
        }
        /// <summary>
        /// Test the property 'CountryOriginAlt'
        /// </summary>
        [Test]
        public void CountryOriginAltTest()
        {
            // TODO unit test for the property 'CountryOriginAlt'
        }
        /// <summary>
        /// Test the property 'CountriesOriginTop'
        /// </summary>
        [Test]
        public void CountriesOriginTopTest()
        {
            // TODO unit test for the property 'CountriesOriginTop'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'RegionOrigin'
        /// </summary>
        [Test]
        public void RegionOriginTest()
        {
            // TODO unit test for the property 'RegionOrigin'
        }
        /// <summary>
        /// Test the property 'TopRegionOrigin'
        /// </summary>
        [Test]
        public void TopRegionOriginTest()
        {
            // TODO unit test for the property 'TopRegionOrigin'
        }
        /// <summary>
        /// Test the property 'SubRegionOrigin'
        /// </summary>
        [Test]
        public void SubRegionOriginTest()
        {
            // TODO unit test for the property 'SubRegionOrigin'
        }
        /// <summary>
        /// Test the property 'ProbabilityCalibrated'
        /// </summary>
        [Test]
        public void ProbabilityCalibratedTest()
        {
            // TODO unit test for the property 'ProbabilityCalibrated'
        }
        /// <summary>
        /// Test the property 'ProbabilityAltCalibrated'
        /// </summary>
        [Test]
        public void ProbabilityAltCalibratedTest()
        {
            // TODO unit test for the property 'ProbabilityAltCalibrated'
        }

    }

}
