/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.8
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.namsor.sdk2.api;
using Org.OpenAPITools.com.namsor.sdk2.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InvoiceItemOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvoiceItemOutTests
    {
        // TODO uncomment below to declare an instance variable for InvoiceItemOut
        //private InvoiceItemOut instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvoiceItemOut
            //instance = new InvoiceItemOut();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvoiceItemOut
        /// </summary>
        [Test]
        public void InvoiceItemOutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvoiceItemOut
            //Assert.IsInstanceOfType<InvoiceItemOut> (instance, "variable 'instance' is a InvoiceItemOut");
        }


        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Test]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Test]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'SubscriptionItem'
        /// </summary>
        [Test]
        public void SubscriptionItemTest()
        {
            // TODO unit test for the property 'SubscriptionItem'
        }
        /// <summary>
        /// Test the property 'InvoiceItemType'
        /// </summary>
        [Test]
        public void InvoiceItemTypeTest()
        {
            // TODO unit test for the property 'InvoiceItemType'
        }
        /// <summary>
        /// Test the property 'PlanNickname'
        /// </summary>
        [Test]
        public void PlanNicknameTest()
        {
            // TODO unit test for the property 'PlanNickname'
        }
        /// <summary>
        /// Test the property 'PlanDesc'
        /// </summary>
        [Test]
        public void PlanDescTest()
        {
            // TODO unit test for the property 'PlanDesc'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [Test]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }

    }

}
