/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.9
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.namsor.sdk2.api;
using Org.OpenAPITools.com.namsor.sdk2.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NameMatchCandidateOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NameMatchCandidateOutTests
    {
        // TODO uncomment below to declare an instance variable for NameMatchCandidateOut
        //private NameMatchCandidateOut instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NameMatchCandidateOut
            //instance = new NameMatchCandidateOut();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NameMatchCandidateOut
        /// </summary>
        [Test]
        public void NameMatchCandidateOutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NameMatchCandidateOut
            //Assert.IsInstanceOfType<NameMatchCandidateOut> (instance, "variable 'instance' is a NameMatchCandidateOut");
        }


        /// <summary>
        /// Test the property 'CandidateName'
        /// </summary>
        [Test]
        public void CandidateNameTest()
        {
            // TODO unit test for the property 'CandidateName'
        }
        /// <summary>
        /// Test the property 'Probability'
        /// </summary>
        [Test]
        public void ProbabilityTest()
        {
            // TODO unit test for the property 'Probability'
        }

    }

}
