/* 
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.8
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.namsor.sdk2.api;
using Org.OpenAPITools.com.namsor.sdk2.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PersonalNameGeoOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PersonalNameGeoOutTests
    {
        // TODO uncomment below to declare an instance variable for PersonalNameGeoOut
        //private PersonalNameGeoOut instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PersonalNameGeoOut
            //instance = new PersonalNameGeoOut();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PersonalNameGeoOut
        /// </summary>
        [Test]
        public void PersonalNameGeoOutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PersonalNameGeoOut
            //Assert.IsInstanceOfType<PersonalNameGeoOut> (instance, "variable 'instance' is a PersonalNameGeoOut");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountryAlt'
        /// </summary>
        [Test]
        public void CountryAltTest()
        {
            // TODO unit test for the property 'CountryAlt'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'TopRegion'
        /// </summary>
        [Test]
        public void TopRegionTest()
        {
            // TODO unit test for the property 'TopRegion'
        }
        /// <summary>
        /// Test the property 'SubRegion'
        /// </summary>
        [Test]
        public void SubRegionTest()
        {
            // TODO unit test for the property 'SubRegion'
        }
        /// <summary>
        /// Test the property 'CountriesTop'
        /// </summary>
        [Test]
        public void CountriesTopTest()
        {
            // TODO unit test for the property 'CountriesTop'
        }
        /// <summary>
        /// Test the property 'ProbabilityCalibrated'
        /// </summary>
        [Test]
        public void ProbabilityCalibratedTest()
        {
            // TODO unit test for the property 'ProbabilityCalibrated'
        }
        /// <summary>
        /// Test the property 'ProbabilityAltCalibrated'
        /// </summary>
        [Test]
        public void ProbabilityAltCalibratedTest()
        {
            // TODO unit test for the property 'ProbabilityAltCalibrated'
        }

    }

}
